export type EndpointType = 
| "age_ratings"
| "age_rating_content_descriptions"
| "alternative_names"
| "artworks"
| "characters"
| "character_mug_shots"
| "collections"
| "collection_memberships"
| "collection_membership_types"
| "collection_relations"
| "collection_relation_types"
| "collection_types"
| "companies"
| "company_logos"
| "company_websites"
| "covers"
| "events"
| "event_logos"
| "event_networks"
| "external_games"
| "franchises"
| "games"
| "game_engines"
| "game_engine_logos"
| "game_localizations"
| "game_modes"
| "game_versions"
| "game_version_features"
| "game_version_feature_values"
| "game_videos"
| "genres"
| "involved_companies"
| "keywords"
| "language_supports"
| "language_support_types"
| "languages"
| "multiplayer_modes"
| "multiquery"
| "network_types"
| "platforms"
| "platform_families"
| "platform_logos"
| "platform_versions"
| "platform_version_companies"
| "platform_version_release_dates"
| "platform_websites"
| "player_perspectives"
| "regions"
| "release_dates"
| "release_date_statuses"
| "screenshots"
| "search"
| "themes"
| "websites";

export type WebhookMethodType = 'create' | 'delete' | 'update';

export interface ICreateWebhook {
    url: string;
    method: WebhookMethodType;
    secret: string;
}
